# Pandas : Data Management

**Method**

- df.sample()
- df.copy()

In [53]:
from datasets import load_dataset
import pandas as pd

raw = load_dataset('lukebarousse/data_jobs')
df =raw['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)

In [54]:
df

             job_title_short  ...                                    job_type_skills
0       Senior Data Engineer  ...                                                NaN
1               Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2              Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3              Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4              Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                      ...  ...                                                ...
785736     Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737          Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738      Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739         Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740     Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[785741 rows x 17 columns]

**df.sample() Method**

In [55]:
# this sample method is use to show a random records. 
df.sample()

       job_title_short  ...                                    job_type_skills
634086   Data Engineer  ...  {'cloud': ['azure', 'aws'], 'programming': ['n...

[1 rows x 17 columns]

In [56]:
# Now with index
df.sample(10)
# everytime you run this it will display other random records from the dataset

                  job_title_short  ...                                    job_type_skills
494307              Data Engineer  ...  {'cloud': ['aws', 'databricks'], 'libraries': ...
709834             Data Scientist  ...                                                NaN
532366      Senior Data Scientist  ...                        {'programming': ['python']}
668521       Senior Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure', ...
86558   Machine Learning Engineer  ...  {'cloud': ['aws'], 'libraries': ['pytorch', 't...
749485           Business Analyst  ...      {'analyst_tools': ['sap'], 'other': ['flow']}
761328               Data Analyst  ...                           {'programming': ['sql']}
123997          Software Engineer  ...                                                NaN
637620               Data Analyst  ...                           {'programming': ['sql']}
303951               Data Analyst  ...  {'analyst_tools': ['sas', 'tableau', 'power bi...

[10 rows x 17 columns]

In [57]:
# There is a way that you can set the record static.
df.sample(10,random_state=42)

              job_title_short  ...                                    job_type_skills
502901   Senior Data Engineer  ...  {'cloud': ['azure'], 'other': ['git'], 'progra...
406337  Senior Data Scientist  ...  {'analyst_tools': ['looker'], 'cloud': ['bigqu...
659951          Data Engineer  ...                                                NaN
541593           Data Analyst  ...                                {'async': ['jira']}
425158   Senior Data Engineer  ...                        {'programming': ['python']}
183426           Data Analyst  ...  {'analyst_tools': ['tableau'], 'cloud': ['orac...
287790           Data Analyst  ...  {'analyst_tools': ['excel'], 'libraries': ['ha...
541983           Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau', 'qli...
416896         Data Scientist  ...                                                NaN
780907          Data Engineer  ...  {'analyst_tools': ['alteryx'], 'cloud': ['orac...

[10 rows x 17 columns]

**df.copy() Method**

**NOTE:**
- This copy method is used to copy the data. Why do we need to use this when we have a '=' assignment operator
- This assignment operator will modify the raw dataset also. for example a = b.
- if we modify the b, a also gets modified when using the assignment operator
- To avoid the original records from being modified, we use the copy() method

In [58]:
df_original = df.copy() ## Here i make a copy of df and store it in the df_original 
## if i make any change in the df_original, it will not change anything in the df. 

df_copy = df_original ## Here i use assignment operator '=' to assign the df_original to df_copy 
## if i make any change in the df_copy, it will also reflect in the df_original 

print(df_copy.loc[:,'salary_rate':'salary_hour_avg'].dropna(subset=['salary_rate']))

print()
print(id(df))
print(id(df_copy))
print(id(df)==id(df_copy))

# both id's are same if we modify the df_copy, df also get modify. This is a major problem, we lost the original dataset. 
# so to protect the original dataset, we need to use this copy() method

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]

1411776472768
1413042216336
False

**Demonstration**

In [59]:
median_yearly_salary = df.salary_year_avg.median()
print('median_yearly_salary: ',median_yearly_salary)

median_hourly_salary = df.salary_hour_avg.median()
print('median_hourly_salary: ',median_hourly_salary)

median_yearly_salary:  115000.0
median_hourly_salary:  45.97999954223633

In [60]:
df_copy['salary_year_avg'] = df_copy['salary_year_avg'].fillna(median_yearly_salary)
df_copy['salary_hour_avg'] = df_copy['salary_hour_avg'].fillna(median_hourly_salary)

df_copy.loc[:,'salary_rate':'salary_hour_avg'].dropna()

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0            45.98
43            hour         115000.0            97.50
51            hour         115000.0            72.50
77            year         140000.0            45.98
92            year         120000.0            45.98
...            ...              ...              ...
785624        year         139216.0            45.98
785641        year         150000.0            45.98
785648        year         221875.0            45.98
785682        year         157500.0            45.98
785692        year         157500.0            45.98

[33067 rows x 3 columns]

In [61]:
df_original.loc[:,'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')
# Look i modify the df_copy but the df_original also get modified

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0            45.98
43            hour         115000.0            97.50
51            hour         115000.0            72.50
77            year         140000.0            45.98
92            year         120000.0            45.98
...            ...              ...              ...
785624        year         139216.0            45.98
785641        year         150000.0            45.98
785648        year         221875.0            45.98
785682        year         157500.0            45.98
785692        year         157500.0            45.98

[33067 rows x 3 columns]

In [62]:
df.loc[:,'salary_rate':'salary_hour_avg'].dropna(subset='salary_rate')
# Look this the original df doesn't change

       salary_rate  salary_year_avg  salary_hour_avg
28            year         109500.0              NaN
43            hour              NaN             97.5
51            hour              NaN             72.5
77            year         140000.0              NaN
92            year         120000.0              NaN
...            ...              ...              ...
785624        year         139216.0              NaN
785641        year         150000.0              NaN
785648        year         221875.0              NaN
785682        year         157500.0              NaN
785692        year         157500.0              NaN

[33067 rows x 3 columns]