# Pandas: Cleaning

For this cleaning section, I'm going to create a new dataframe because I didn't want to change anything in the raw file. So I create a copy and name it as df1

**Methods**

- pd.to_datetime()
- .dt.month
- sort_values()
- drop()
- dropna()

In [19]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset('lukebarousse/data_jobs')
raw=dataset['train'].to_pandas()
df = None
df = raw.copy()
df
# Dataset

             job_title_short  ...                                    job_type_skills
0       Senior Data Engineer  ...                                                NaN
1               Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2              Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3              Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4              Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                      ...  ...                                                ...
785736     Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737          Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738      Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739         Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740     Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[785741 rows x 17 columns]

In [20]:
df.info()
# why we are looking at this because the job_posted_date column type is not in datetime format, it's in the format of str

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  str
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), float64(2), str(12)
memory usage: 279.3 MB

**pd.to_datetime() Method**

In [21]:
df['job_posted_date']=pd.to_datetime(df.job_posted_date)

In [22]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

**.dt.month**

In [23]:
df['job_posted_month'] = df.job_posted_date.dt.month

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
 17  job_posted_month       785741 non-null  int32
dtypes: bool(3), datetime64[us](1), float64(2), int32(1), str(11)
memory usage: 268.1 MB

**sort_values() Method**

In [25]:
# Dataset OverView Before using Sort_values() Method
df

             job_title_short  ... job_posted_month
0       Senior Data Engineer  ...                6
1               Data Analyst  ...                1
2              Data Engineer  ...               10
3              Data Engineer  ...                7
4              Data Engineer  ...                8
...                      ...  ...              ...
785736     Software Engineer  ...                3
785737          Data Analyst  ...                3
785738      Business Analyst  ...                3
785739         Data Engineer  ...                3
785740     Software Engineer  ...                3

[785741 rows x 18 columns]

In [26]:
df.job_posted_date.sort_values()

108804   2023-01-01 00:00:04
96906    2023-01-01 00:00:07
98438    2023-01-01 00:00:22
110290   2023-01-01 00:00:24
72158    2023-01-01 00:00:27
                 ...
362129   2023-12-31 23:40:31
351830   2023-12-31 23:40:31
327439   2023-12-31 23:40:32
112373   2023-12-31 23:59:58
90102    2023-12-31 23:59:58
Name: job_posted_date, Length: 785741, dtype: datetime64[us]

In [27]:
# using inplace = True in the sort_values method to freeze the asc order 
df.sort_values('job_posted_date',inplace=True)

In [28]:
df

                  job_title_short  ... job_posted_month
108804               Data Analyst  ...                1
96906                Data Analyst  ...                1
98438                Data Analyst  ...                1
110290               Data Analyst  ...                1
72158         Senior Data Analyst  ...                1
...                           ...  ...              ...
362129              Data Engineer  ...               12
351830              Data Engineer  ...               12
327439              Data Engineer  ...               12
112373        Senior Data Analyst  ...               12
90102   Machine Learning Engineer  ...               12

[785741 rows x 18 columns]

**drop() Method**

In [29]:
df.drop(labels='salary_hour_avg',axis= 1,inplace=True)

In [30]:
df

                  job_title_short  ... job_posted_month
108804               Data Analyst  ...                1
96906                Data Analyst  ...                1
98438                Data Analyst  ...                1
110290               Data Analyst  ...                1
72158         Senior Data Analyst  ...                1
...                           ...  ...              ...
362129              Data Engineer  ...               12
351830              Data Engineer  ...               12
327439              Data Engineer  ...               12
112373        Senior Data Analyst  ...               12
90102   Machine Learning Engineer  ...               12

[785741 rows x 17 columns]

**dropna() Method**

In [31]:
df.dropna(subset='salary_year_avg',axis=0,inplace=True)

In [32]:
df.info()

<class 'pandas.DataFrame'>
Index: 22003 entries, 108883 to 327439
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   job_title_short        22003 non-null  str
 1   job_title              22003 non-null  str
 2   job_location           21723 non-null  str
 3   job_via                22003 non-null  str
 4   job_schedule_type      21987 non-null  str
 5   job_work_from_home     22003 non-null  bool
 6   search_location        22003 non-null  str
 7   job_posted_date        22003 non-null  datetime64[us]
 8   job_no_degree_mention  22003 non-null  bool
 9   job_health_insurance   22003 non-null  bool
 10  job_country            22003 non-null  str
 11  salary_rate            22003 non-null  str
 12  salary_year_avg        22003 non-null  float64
 13  company_name           22003 non-null  str
 14  job_skills             20170 non-null  str
 15  job_type_skills        20170 non-null  str
 16  job_posted_month       22003 non-null  int32
dtypes: bool(3), datetime64[us](1), float64(1), int32(1), str(11)
memory usage: 8.1 MB