# Pandas : Analysis

**Methods:**

- count()
- sum()
- cumsum()
- min()
- max()
- idxmin()
- idxmax()
- mean()
- median()
- mode()
- value_counts()
- groupby()

In [2]:
from datasets import load_dataset
import pandas as pd

dataset = load_dataset('lukebarousse/data_jobs')
raw=dataset['train'].to_pandas()
df = None
df = raw.copy()
# Dataset 
df['job_posted_date']=pd.to_datetime(df.job_posted_date)
df.info()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

**count() Method**

In [3]:
df.count()

job_title_short          785741
job_title                785740
job_location             784696
job_via                  785733
job_schedule_type        773074
job_work_from_home       785741
search_location          785741
job_posted_date          785741
job_no_degree_mention    785741
job_health_insurance     785741
job_country              785692
salary_rate               33067
salary_year_avg           22003
salary_hour_avg           10662
company_name             785723
job_skills               668704
job_type_skills          668704
dtype: int64

**sum() Method**

In [4]:
df['salary_year_avg'].sum()

np.float64(2712667888.4023438)

**cumsum() Method**

In [6]:
df['salary_year_avg'].notna().cumsum()

0             0
1             0
2             0
3             0
4             0
          ...
785736    22003
785737    22003
785738    22003
785739    22003
785740    22003
Name: salary_year_avg, Length: 785741, dtype: int64

**min() Method**

In [8]:
df['salary_year_avg'].min()

np.float64(15000.0)

**max() Method**

In [9]:
df['salary_year_avg'].max()

np.float64(960000.0)

**idxmin() Method**

In [ ]:
df['salary_year_avg'].idxmin()

665729

In [12]:
min_salary =df['salary_year_avg'].idxmin()
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

**idxmax() Method**

In [13]:
df['salary_year_avg'].idxmax()

554784

In [14]:
max_salary = df['salary_year_avg'].idxmax()
df.iloc[max_salary]

job_title_short                                           Data Scientist
job_title                                                 Data Scientist
job_location                                                 Madison, SD
job_via                                    via Cooperative Career Center
job_schedule_type                                              Full-time
job_work_from_home                                                 False
search_location                                  Illinois, United States
job_posted_date                                      2023-05-04 19:06:06
job_no_degree_mention                                              False
job_health_insurance                                                True
job_country                                                United States
salary_rate                                                         year
salary_year_avg                                                 960000.0
salary_hour_avg                                                      NaN
company_name                 East River Electric Power Cooperative, Inc.
job_skills                                ['java', 'c++', 'python', 'r']
job_type_skills          {'programming': ['java', 'c++', 'python', 'r']}
Name: 554784, dtype: object

**mean() Method**

In [15]:
df['salary_year_avg'].mean()

np.float64(123286.27407182401)

**median() Method**

In [16]:
df['salary_year_avg'].median()

np.float64(115000.0)

**mode() Method**

In [17]:
df['salary_year_avg'].mode()

0    90000.0
Name: salary_year_avg, dtype: float64

**value_counts() Method**

The value_counts() method finds all unique items in a Pandas column and counts exactly how many times each one appears. It then automatically displays these items as a sorted list, placing the most frequent values at the very top.

In [ ]:
df['job_title_short'].value_counts() # it count the total unique

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

**groupby() Method**

In [20]:
df.groupby('job_title_short')['salary_year_avg'].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [22]:
df.groupby(['job_title_short','job_country'])['salary_year_avg'].max()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      79200.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        79200.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

In [26]:
df.groupby('job_title_short')[['salary_year_avg','salary_hour_avg']].mean()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst              91082.612833        42.723415
Cloud Engineer               111268.453846        45.560715
Data Analyst                  93841.907854        38.106918
Data Engineer                130125.604250        57.196998
Data Scientist               135988.837171        49.361403
Machine Learning Engineer    126774.315972        48.477935
Senior Data Analyst          113911.363665        47.661218
Senior Data Engineer         145840.611624        62.848496
Senior Data Scientist        154206.292996        54.105631
Software Engineer            113393.760054        46.452019

In [28]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min','max','mean','median','count'])

                               min       max           mean    median  count
job_title_short
Business Analyst           16500.0  387460.0   91082.612833   85000.0    610
Cloud Engineer             42000.0  280000.0  111268.453846   90000.0     65
Data Analyst               25000.0  650000.0   93841.907854   90000.0   5451
Data Engineer              15000.0  525000.0  130125.604250  125000.0   4500
Data Scientist             27000.0  960000.0  135988.837171  127500.0   5922
Machine Learning Engineer  30000.0  325000.0  126774.315972  106415.0    576
Senior Data Analyst        30000.0  425000.0  113911.363665  111175.0   1131
Senior Data Engineer       35000.0  425000.0  145840.611624  147500.0   1591
Senior Data Scientist      45000.0  890000.0  154206.292996  155500.0   1690
Software Engineer          28000.0  375000.0  113393.760054   99150.0    467

In [30]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min','max','mean','median','count']).sort_values('count')

                               min       max           mean    median  count
job_title_short
Cloud Engineer             42000.0  280000.0  111268.453846   90000.0     65
Software Engineer          28000.0  375000.0  113393.760054   99150.0    467
Machine Learning Engineer  30000.0  325000.0  126774.315972  106415.0    576
Business Analyst           16500.0  387460.0   91082.612833   85000.0    610
Senior Data Analyst        30000.0  425000.0  113911.363665  111175.0   1131
Senior Data Engineer       35000.0  425000.0  145840.611624  147500.0   1591
Senior Data Scientist      45000.0  890000.0  154206.292996  155500.0   1690
Data Engineer              15000.0  525000.0  130125.604250  125000.0   4500
Data Analyst               25000.0  650000.0   93841.907854   90000.0   5451
Data Scientist             27000.0  960000.0  135988.837171  127500.0   5922