# Pandas : Exporting Data
**Methods**
- .to_clipboard()
- .to_excel()
- .to_csv()
- .to_parquet()
- .to_pickle()

In [1]:
# Import libraries
from datasets import load_dataset as ld
import pandas as pd

# Load Dataset
raw = ld('lukebarousse/data_jobs')
data =raw['train'].to_pandas()
df = data.copy()

# Convert string into date 
df['job_posted_date']=pd.to_datetime(df.job_posted_date)
df.info()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB

In [2]:
df

             job_title_short  ...                                    job_type_skills
0       Senior Data Engineer  ...                                                NaN
1               Data Analyst  ...  {'analyst_tools': ['power bi', 'tableau'], 'pr...
2              Data Engineer  ...  {'analyst_tools': ['dax'], 'cloud': ['azure'],...
3              Data Engineer  ...  {'cloud': ['aws'], 'libraries': ['tensorflow',...
4              Data Engineer  ...  {'cloud': ['oracle', 'aws'], 'other': ['ansibl...
...                      ...  ...                                                ...
785736     Software Engineer  ...  {'os': ['linux', 'unix'], 'other': ['kubernete...
785737          Data Analyst  ...  {'analyst_tools': ['sas', 'excel'], 'programmi...
785738      Business Analyst  ...         {'analyst_tools': ['powerpoint', 'excel']}
785739         Data Engineer  ...  {'cloud': ['aws', 'snowflake', 'azure', 'redsh...
785740     Software Engineer  ...              {'cloud': ['aws'], 'other': ['flow']}

[785741 rows x 17 columns]

In [4]:
df['job_posted_month'] = df['job_posted_date'].dt.strftime('%b')
df

             job_title_short  ... job_posted_month
0       Senior Data Engineer  ...              Jun
1               Data Analyst  ...              Jan
2              Data Engineer  ...              Oct
3              Data Engineer  ...              Jul
4              Data Engineer  ...              Aug
...                      ...  ...              ...
785736     Software Engineer  ...              Mar
785737          Data Analyst  ...              Mar
785738      Business Analyst  ...              Mar
785739         Data Engineer  ...              Mar
785740     Software Engineer  ...              Mar

[785741 rows x 18 columns]

In [6]:
months=df['job_posted_month'].unique()
months

<ArrowStringArray>
['Jun', 'Jan', 'Oct', 'Jul', 'Aug', 'Nov', 'Mar', 'Dec', 'Apr', 'Feb', 'Sep',
 'May']
Length: 12, dtype: str

In [9]:
dict_months={month : df[df['job_posted_month']== month] for month in months}

In [13]:
q1 = pd.concat([dict_months['Jan'],dict_months['Feb'],dict_months['Mar']])
q1

          job_title_short  ... job_posted_month
1            Data Analyst  ...              Jan
20         Data Scientist  ...              Jan
39          Data Engineer  ...              Jan
53          Data Engineer  ...              Jan
55         Data Scientist  ...              Jan
...                   ...  ...              ...
785736  Software Engineer  ...              Mar
785737       Data Analyst  ...              Mar
785738   Business Analyst  ...              Mar
785739      Data Engineer  ...              Mar
785740  Software Engineer  ...              Mar

[220484 rows x 18 columns]

**clipboard() Method**

In [ ]:
q1.head().to_clipboard(sep=',')
# this clipboard method is use to copy the values and help us to paste it using ctrl + v.
# But this function have a limitation we cannot copy too many values if you do it may run into errors

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,job_posted_month
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,,,,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']","{'analyst_tools': ['power bi', 'tableau'], 'programming': ['r', 'python', 'sql', 'nosql']}",Jan
20,Data Scientist,Data Scientist,"Zaventem, Belgium",via BeBee Belgique,Full-time,False,Belgium,2023-01-31 13:53:38,False,False,Belgium,,,,Devoteam,"['r', 'python', 'sql', 'pandas', 'numpy', 'scikit-learn', 'matplotlib', 'hadoop', 'spark']","{'libraries': ['pandas', 'numpy', 'scikit-learn', 'matplotlib', 'hadoop', 'spark'], 'programming': ['r', 'python', 'sql']}",Jan
39,Data Engineer,Data Engineer,"Fort Worth, TX",via LinkedIn,Full-time,False,"Texas, United States",2023-01-25 13:24:01,False,False,United States,,,,Programmers.io,"['sql', 'python']","{'programming': ['sql', 'python']}",Jan
53,Data Engineer,Data Engineer,"San Mateo, CA",via LinkedIn,Full-time,False,"California, United States",2023-01-28 13:07:30,False,True,United States,,,,Verkada,"['sql', 'python', 'aws', 'looker']","{'analyst_tools': ['looker'], 'cloud': ['aws'], 'programming': ['sql', 'python']}",Jan
55,Data Scientist,Data Scientist,"São Paulo, State of São Paulo, Brazil",via BeBee,Full-time,False,Brazil,2023-01-03 23:02:27,False,False,Brazil,,,,Mars,"['python', 'sql', 'azure']","{'cloud': ['azure'], 'programming': ['python', 'sql']}",Jan

**to_csv() Method**

In [21]:
q1.to_csv('Quater 1.csv')
# This method help us to make or export the file we want as a .csv file 
# You may see this .csv file in the folder 
# this function need to mention the extension like .csv after the name of the file inside the parantheses, 
# otherwise it may save the file as text file without any extension.

In [22]:
# to open the file, look at the file it have a column called unnamed:0, we don't want that let's remove it by using index col =0
pd.read_csv(r'C:\Users\rishi\OneDrive\Documents\Python_Data_Project\2_Advance\Pandas_Chapter_2\Quater 1.csv',index_col=0)

          job_title_short  ... job_posted_month
1            Data Analyst  ...              Jan
20         Data Scientist  ...              Jan
39          Data Engineer  ...              Jan
53          Data Engineer  ...              Jan
55         Data Scientist  ...              Jan
...                   ...  ...              ...
785736  Software Engineer  ...              Mar
785737       Data Analyst  ...              Mar
785738   Business Analyst  ...              Mar
785739      Data Engineer  ...              Mar
785740  Software Engineer  ...              Mar

[220484 rows x 18 columns]

**to_excel_Method**

In [ ]:
q1.to_excel('Quater 1 as excel file.xlsx')
# This method help us to make or export the file we want as a .xlsx file 
# You may see this .xlsx file in the folder 
# this function need to mention the extension like .xlsx after the name of the file inside the parantheses, 
# otherwise it may save the file as text file without any extension.
# this excel file have a million record limitation and to export and read this .xlsx file is slow. 
# so if you have more records go with the parquet() or pickel() file type.

In [24]:
# to open the file, look at the file it have a column called unnamed:0, we don't want that let's remove it by using index col =0
pd.read_excel(r'C:\Users\rishi\OneDrive\Documents\Python_Data_Project\2_Advance\Pandas_Chapter_2\Quater 1 as excel file.xlsx')

        Unnamed: 0  ... job_posted_month
0                1  ...              Jan
1               20  ...              Jan
2               39  ...              Jan
3               53  ...              Jan
4               55  ...              Jan
...            ...  ...              ...
220479      785736  ...              Mar
220480      785737  ...              Mar
220481      785738  ...              Mar
220482      785739  ...              Mar
220483      785740  ...              Mar

[220484 rows x 19 columns]

**to_parquet() Method**

In [25]:
q1.to_parquet('Quater 1 as parquet file.parquet')

In [26]:
pd.read_parquet(r'C:\Users\rishi\OneDrive\Documents\Python_Data_Project\2_Advance\Pandas_Chapter_2\Quater 1 as parquet file.parquet')

          job_title_short  ... job_posted_month
1            Data Analyst  ...              Jan
20         Data Scientist  ...              Jan
39          Data Engineer  ...              Jan
53          Data Engineer  ...              Jan
55         Data Scientist  ...              Jan
...                   ...  ...              ...
785736  Software Engineer  ...              Mar
785737       Data Analyst  ...              Mar
785738   Business Analyst  ...              Mar
785739      Data Engineer  ...              Mar
785740  Software Engineer  ...              Mar

[220484 rows x 18 columns]

**to_pickel() Method**

In [27]:
q1.to_pickle('Quater 1 as pickel file.pickel')

In [28]:
pd.read_pickle(r'C:\Users\rishi\OneDrive\Documents\Python_Data_Project\2_Advance\Pandas_Chapter_2\Quater 1 as pickel file.pickel')

          job_title_short  ... job_posted_month
1            Data Analyst  ...              Jan
20         Data Scientist  ...              Jan
39          Data Engineer  ...              Jan
53          Data Engineer  ...              Jan
55         Data Scientist  ...              Jan
...                   ...  ...              ...
785736  Software Engineer  ...              Mar
785737       Data Analyst  ...              Mar
785738   Business Analyst  ...              Mar
785739      Data Engineer  ...              Mar
785740  Software Engineer  ...              Mar

[220484 rows x 18 columns]