# Pandas : Apply_Functions

**Methods**
- df.apply()
- lambda
- ast.literal_eval()
- def function
- notna()
- isna()

In [2]:
# Import libraries 
from datasets import load_dataset
import pandas as pd
import ast

# load dataset
raw=load_dataset('lukebarousse/data_jobs')
data = raw['train'].to_pandas()
df = data.copy()
df_job = data.copy()

# String to Date Conversion 
df['job_posted_date'] = pd.to_datetime(df.job_posted_date)
df_job['job_posted_date'] = pd.to_datetime(df_job.job_posted_date)
print(df.info())
df

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

<class 'pandas.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  str
 1   job_title              785740 non-null  str
 2   job_location           784696 non-null  str
 3   job_via                785733 non-null  str
 4   job_schedule_type      773074 non-null  str
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  str
 7   job_posted_date        785741 non-null  datetime64[us]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  str
 11  salary_rate            33067 non-null   str
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  str
 15  job_skills             668704 non-null  str
 16  job_type_skills        668704 non-null  str
dtypes: bool(3), datetime64[us](1), float64(2), str(11)
memory usage: 265.1 MB
None

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

**removing NaN values using notna() method**

**1. The challenge is to add salary year inflated by 1.03**

In [3]:
df['salary_year_avg']

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
785736   NaN
785737   NaN
785738   NaN
785739   NaN
785740   NaN
Name: salary_year_avg, Length: 785741, dtype: float64

In [4]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [5]:
df_salary=df[pd.notna(df['salary_year_avg'])]
df_salary

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
28,Data Scientist,CRM Data Specialist,"San José Province, San José, Costa Rica",via Ai-Jobs.net,Full-time,False,Costa Rica,2023-08-01 13:37:57,False,False,Costa Rica,year,109500.0,NaN,Netskope,"['gdpr', 'excel']","{'analyst_tools': ['excel'], 'libraries': ['gd..."
77,Data Engineer,Data Engineer,"Arlington, VA",via LinkedIn,Full-time,False,Sudan,2023-06-26 14:22:54,False,False,Sudan,year,140000.0,NaN,Intelletec,"['mongodb', 'mongodb', 'python', 'r', 'sql', '...","{'analyst_tools': ['tableau'], 'cloud': ['orac..."
92,Data Engineer,Remote - Data Engineer - Permanent - W2,Anywhere,via LinkedIn,Full-time,True,"Illinois, United States",2023-02-21 13:29:59,False,True,United States,year,120000.0,NaN,Apex Systems,"['sql', 'python']","{'programming': ['sql', 'python']}"
100,Data Scientist,"Data Scientist, Risk Data Mining - USDS","Mountain View, CA",via LinkedIn,Full-time,False,"California, United States",2023-07-31 13:01:18,False,True,United States,year,228222.0,NaN,TikTok,"['sql', 'r', 'python', 'express']","{'programming': ['sql', 'r', 'python'], 'webfr..."
109,Data Analyst,Senior Supply Chain Analytics Analyst,Anywhere,via Get.It,Full-time,True,"Illinois, United States",2023-10-12 13:02:19,False,True,United States,year,89000.0,NaN,Get It Recruit - Transportation,"['python', 'r', 'alteryx', 'tableau']","{'analyst_tools': ['alteryx', 'tableau'], 'pro..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785624,Data Engineer,Data Analytics Engineer (Hybrid),"Mt Prospect, IL",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-08-31 06:02:16,False,True,United States,year,139216.0,NaN,Bosch Group,"['go', 'python', 'r', 'sql', 'oracle', 'window...","{'analyst_tools': ['alteryx', 'power bi', 'tab..."
785641,Data Engineer,Data Engineer,"New York, NY",via Dice,Full-time,False,Georgia,2023-01-04 16:36:07,True,False,United States,year,150000.0,NaN,"Engage Partners, Inc.",NaN,NaN
785648,Data Scientist,Director Data Scientist - Commercial Platforms...,"Pleasant Hill, CA",via Ai-Jobs.net,Full-time,False,"California, United States",2023-04-12 06:02:51,False,True,United States,year,221875.0,NaN,84.51°,"['python', 'azure', 'snowflake', 'spark']","{'cloud': ['azure', 'snowflake'], 'libraries':..."
785682,Data Scientist,Data Scientist für datengetriebene Entwicklung...,"Reutlingen, Germany",via Ai-Jobs.net,Full-time,False,Germany,2023-03-04 06:16:08,False,False,Germany,year,157500.0,NaN,Bosch Group,"['python', 'hadoop', 'spark', 'airflow', 'kube...","{'libraries': ['hadoop', 'spark', 'airflow'], ..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"

*1. Method Used*
- function def
- apply() method

In [6]:
def projected_salary(salary):
    return salary*1.03

df_salary['salary_year_inflated'] = df['salary_year_avg'].apply(projected_salary)

df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [7]:
df_salary.drop('salary_year_inflated',axis= 1,inplace = True)

*2. Method_Used*
- lambda
- apply

In [8]:
df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(lambda salary : salary*1.03)
df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [9]:
df_salary.drop('salary_year_inflated',axis= 1,inplace = True)

*3. Method Used*

In [10]:
df_salary['salary_year_inflated'] = df['salary_year_avg']*1.03
df_salary[['salary_year_avg','salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [11]:
df_salary.drop('salary_year_inflated',axis= 1,inplace = True)

**2. The challenge is to change the job_skill column into list type from string**

In [12]:
print(type(df['job_skills'][8]))
df['job_skills'][8]

<class 'str'>

"['excel', 'powerpoint', 'power bi']"

In [13]:
print(type(ast.literal_eval(df.job_skills[7])))
ast.literal_eval(df.job_skills[7])

<class 'list'>

['sql',
 'nosql',
 'gcp',
 'azure',
 'aws',
 'bigquery',
 'databricks',
 'redshift',
 'airflow',
 'kafka',
 'spark']

*1. Method*

In [14]:
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)

df['job_skills'] = df['job_skills'].apply(clean_list)

In [15]:
df[['job_skills']].head(20)

                                           job_skills
0                                                None
1          [r, python, sql, nosql, power bi, tableau]
2   [python, sql, c#, azure, airflow, dax, docker,...
3   [python, c++, java, matlab, aws, tensorflow, k...
4   [bash, python, oracle, aws, ansible, puppet, j...
5                                  [python, sql, gcp]
6   [sql, python, java, sql server, gcp, bigquery,...
7   [sql, nosql, gcp, azure, aws, bigquery, databr...
8                       [excel, powerpoint, power bi]
9   [sql, python, r, mongodb, mongodb, sql server,...
10                 [python, databricks, azure, spark]
11                                     [python, qlik]
12             [sql, php, excel, power bi, sap, jira]
13  [python, sql, go, ruby, ruby, javascript, aws,...
14                                 [mongodb, mongodb]
15                            [python, sql, power bi]
16  [powershell, python, sql, mysql, sql server, d...
17                                   [go, apl, excel]
18  [sql, python, r, redshift, pandas, excel, look...
19  [r, sql, python, scala, java, c++, hadoop, tab...

In [16]:
print(type(df_job['job_skills'][9]))
df_job['job_skills'][9]

<class 'str'>

"['sql', 'python', 'r', 'mongodb', 'mongodb', 'sql server', 'azure', 'pandas', 'spark', 'windows', 'excel']"

*2. Method*

In [17]:
df_job['job_skills'] = df_job['job_skills'].apply(lambda skill : ast.literal_eval(skill) if pd.notna(skill) else skill)

In [18]:
print(type(df_job['job_skills'][8]))
df_job[['job_skills']].head(10)

<class 'list'>

                                          job_skills
0                                                NaN
1         [r, python, sql, nosql, power bi, tableau]
2  [python, sql, c#, azure, airflow, dax, docker,...
3  [python, c++, java, matlab, aws, tensorflow, k...
4  [bash, python, oracle, aws, ansible, puppet, j...
5                                 [python, sql, gcp]
6  [sql, python, java, sql server, gcp, bigquery,...
7  [sql, nosql, gcp, azure, aws, bigquery, databr...
8                      [excel, powerpoint, power bi]
9  [sql, python, r, mongodb, mongodb, sql server,...

**3. Calculates Projected salary next year**
- Senior roles assume 5%
- other roles assume 3%

*1. Method*

In [19]:
def projected_salary(row):
    if 'Senior' in row['job_title_short']:
        return row['salary_year_avg']*1.05
    else:
        return row['salary_year_avg']*1.03
    
df_salary['salary_inflated'] = df_salary.apply(projected_salary,axis =1)
df_salary[['job_title_short','salary_year_avg','salary_inflated']].tail(10)

              job_title_short  salary_year_avg  salary_inflated
785340  Senior Data Scientist         196800.0        206640.00
785395          Data Engineer          64800.0         66744.00
785488         Data Scientist         115000.0        118450.00
785515           Data Analyst         105000.0        108150.00
785563         Data Scientist         136400.0        140492.00
785624          Data Engineer         139216.0        143392.48
785641          Data Engineer         150000.0        154500.00
785648         Data Scientist         221875.0        228531.25
785682         Data Scientist         157500.0        162225.00
785692         Data Scientist         157500.0        162225.00

In [20]:
df_salary.drop('salary_inflated',axis=1,inplace = True)

*2. Method*

In [21]:
df_salary['salary_inflated'] = df_salary.apply(lambda row: row['salary_year_avg']*1.05 if 'Senior' in row['job_title_short'] else row['salary_year_avg']*1.03,axis =1 )

In [22]:
df_salary[['job_title_short','salary_year_avg','salary_inflated']]

       job_title_short  salary_year_avg  salary_inflated
28      Data Scientist         109500.0        112785.00
77       Data Engineer         140000.0        144200.00
92       Data Engineer         120000.0        123600.00
100     Data Scientist         228222.0        235068.66
109       Data Analyst          89000.0         91670.00
...                ...              ...              ...
785624   Data Engineer         139216.0        143392.48
785641   Data Engineer         150000.0        154500.00
785648  Data Scientist         221875.0        228531.25
785682  Data Scientist         157500.0        162225.00
785692  Data Scientist         157500.0        162225.00

[22003 rows x 3 columns]